"""auto update

Revision ID: 241bd2928dc8
Revises: 1cbec48e36a6
Create Date: 2026-04-01 05:17:15.671810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '241bd2928dc8'
down_revision: Union[str, Sequence[str], None] = '1cbec48e36a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('customer_kennitala', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('loans', 'salesman_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'license_plate',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'checkout_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               nullable=True)
    op.alter_column('loans', 'returned',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('loans', 'return_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'return_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('loans', 'returned',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'no'::character varying"),
               nullable=False)
    op.alter_column('loans', 'checkout_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('loans', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('loans', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('loans', 'license_plate',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('loans', 'salesman_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('loans', 'notes')
    op.drop_column('loans', 'customer_kennitala')
    # ### end Alembic commands ###